version: '3.5'
services:
  event-service-mysql:
    image: 'mysql:8.4.3'
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=eventdb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./.data/mysql:/var/lib/mysql