version: '3.5'
services:
  ticketing-service-mysql:
    image: 'mysql:8.4.3'
    ports:
      - "3308:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=ticketingdb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./.data/mysql:/var/lib/mysql
  ticketing-service-redis:
    image: redis:7.4.2
    ports:
      - "6379:6379"
    volumes:
      - ./.data/redis:/data