version: '3.5'
services:
  event-service-mysql:
    image: 'mysql:8.4.3'
    ports:
      - "3306:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=eventdb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./.data/mysql:/var/lib/mysql
  event-service-kafka-1:
    image: bitnami/kafka:4.0.0
    ports:
      - "9094:9094"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@event-service-kafka-1:9093,2@event-service-kafka-2:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://event-service-kafka-1:9092,EXTERNAL://localhost:9094
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=event-service-kraft-cluster
    volumes:
      - ./.data/kafka-1:/bitnami/kafka
  event-service-kafka-2:
    image: bitnami/kafka:4.0.0
    ports:
      - "9095:9095"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@event-service-kafka-1:9093,2@event-service-kafka-2:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9095
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://event-service-kafka-2:9092,EXTERNAL://localhost:9095
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=event-service-kraft-cluster
    volumes:
      - ./.data/kafka-2:/bitnami/kafka
  dead-letter-kafka:
    image: bitnami/kafka:4.0.0
    ports:
      - "9096:9096"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@dead-letter-kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://dead-letter-kafka:9092,EXTERNAL://localhost:9096
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=dead-letter-kafka-cluster
    volumes:
      - ./.data/dead-letter-kafka:/bitnami/kafka
  kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8089:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=event-service-kafka-1:9092,event-service-kafka-2:9092
      - KAFKA_CLUSTERS_1_NAME=dead-letter
      - KAFKA_CLUSTERS_1_BOOTSTRAPSERVERS=dead-letter-kafka:9092
    depends_on:
      - event-service-kafka-1
      - event-service-kafka-2
      - dead-letter-kafka