version: '3.5'
services:
  payment-service-mysql:
    image: 'mysql:8.4.3'
    ports:
      - "3307:3306"
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=paymentdb
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    volumes:
      - ./.data/mysql:/var/lib/mysql
  payment-service-kafka-1:
    image: bitnami/kafka:4.0.0
    ports:
      - "9096:9096"
    environment:
      - KAFKA_CFG_NODE_ID=1
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@payment-service-kafka-1:9093,2@payment-service-kafka-2:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9096
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://payment-service-kafka-1:9092,EXTERNAL://localhost:9096
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=payment-service-kraft-cluster
    volumes:
      - ./.data/kafka-1:/bitnami/kafka
  payment-service-kafka-2:
    image: bitnami/kafka:4.0.0
    ports:
      - "9097:9097"
    environment:
      - KAFKA_CFG_NODE_ID=2
      - KAFKA_CFG_PROCESS_ROLES=broker,controller
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@payment-service-kafka-1:9093,2@payment-service-kafka-2:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_LISTENERS=INTERNAL://:9092,CONTROLLER://:9093,EXTERNAL://:9097
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://payment-service-kafka-2:9092,EXTERNAL://localhost:9097
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_KRAFT_CLUSTER_ID=payment-service-kraft-cluster
    volumes:
      - ./.data/kafka-2:/bitnami/kafka
  payment-kafka-ui:
    image: provectuslabs/kafka-ui:v0.7.2
    ports:
      - "8090:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=payment-service-kafka-1:9092,payment-service-kafka-2:9092
    depends_on:
      - payment-service-kafka-1
      - payment-service-kafka-2